/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * AggregateBalance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class AggregateBalance {
  @SerializedName("balanceDefinitionId")
  private String balanceDefinitionId = null;

  @SerializedName("value")
  private BigDecimal value = null;

  public AggregateBalance balanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
    return this;
  }

   /**
   * balance definition ID
   * @return balanceDefinitionId
  **/
  @ApiModelProperty(value = "balance definition ID")
  public String getBalanceDefinitionId() {
    return balanceDefinitionId;
  }

  public void setBalanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
  }

  public AggregateBalance value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Unique identifier for the balance definition associated with this aggregate balance
   * @return value
  **/
  @ApiModelProperty(value = "Unique identifier for the balance definition associated with this aggregate balance")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AggregateBalance aggregateBalance = (AggregateBalance) o;
    return ObjectUtils.equals(this.balanceDefinitionId, aggregateBalance.balanceDefinitionId) &&
    ObjectUtils.equals(this.value, aggregateBalance.value);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(balanceDefinitionId, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregateBalance {\n");
    
    sb.append("    balanceDefinitionId: ").append(toIndentedString(balanceDefinitionId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

