/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Balance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class Balance {
  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("balanceDefinitionId")
  private String balanceDefinitionId = null;

  @SerializedName("consumedAt")
  private String consumedAt = null;

  @SerializedName("contactId")
  private Integer contactId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("expiresAt")
  private String expiresAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  @SerializedName("organizationId")
  private Integer organizationId = null;

  public Balance amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The current amount available in the balance
   * @return amount
  **/
  @ApiModelProperty(value = "The current amount available in the balance")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public Balance balanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
    return this;
  }

   /**
   * balance definition ID
   * @return balanceDefinitionId
  **/
  @ApiModelProperty(value = "balance definition ID")
  public String getBalanceDefinitionId() {
    return balanceDefinitionId;
  }

  public void setBalanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
  }

  public Balance consumedAt(String consumedAt) {
    this.consumedAt = consumedAt;
    return this;
  }

   /**
   * Timestamp of when the balance was last consumed
   * @return consumedAt
  **/
  @ApiModelProperty(value = "Timestamp of when the balance was last consumed")
  public String getConsumedAt() {
    return consumedAt;
  }

  public void setConsumedAt(String consumedAt) {
    this.consumedAt = consumedAt;
  }

  public Balance contactId(Integer contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * contact ID
   * @return contactId
  **/
  @ApiModelProperty(value = "contact ID")
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(Integer contactId) {
    this.contactId = contactId;
  }

  public Balance createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Timestamp of when the balance was created
   * @return createdAt
  **/
  @ApiModelProperty(value = "Timestamp of when the balance was created")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Balance expiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Expiration timestamp of the balance
   * @return expiresAt
  **/
  @ApiModelProperty(value = "Expiration timestamp of the balance")
  public String getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
  }

  public Balance id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the balance
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier for the balance")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Balance loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * loyalty program ID
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "loyalty program ID")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }

  public Balance organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * organization ID
   * @return organizationId
  **/
  @ApiModelProperty(value = "organization ID")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Balance balance = (Balance) o;
    return ObjectUtils.equals(this.amount, balance.amount) &&
    ObjectUtils.equals(this.balanceDefinitionId, balance.balanceDefinitionId) &&
    ObjectUtils.equals(this.consumedAt, balance.consumedAt) &&
    ObjectUtils.equals(this.contactId, balance.contactId) &&
    ObjectUtils.equals(this.createdAt, balance.createdAt) &&
    ObjectUtils.equals(this.expiresAt, balance.expiresAt) &&
    ObjectUtils.equals(this.id, balance.id) &&
    ObjectUtils.equals(this.loyaltyProgramId, balance.loyaltyProgramId) &&
    ObjectUtils.equals(this.organizationId, balance.organizationId);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(amount, balanceDefinitionId, consumedAt, contactId, createdAt, expiresAt, id, loyaltyProgramId, organizationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Balance {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    balanceDefinitionId: ").append(toIndentedString(balanceDefinitionId)).append("\n");
    sb.append("    consumedAt: ").append(toIndentedString(consumedAt)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

