/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BalanceLimit
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class BalanceLimit {
  @SerializedName("balanceDefinitionId")
  private String balanceDefinitionId = null;

  @SerializedName("constraintType")
  private String constraintType = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("durationUnit")
  private String durationUnit = null;

  @SerializedName("durationValue")
  private Integer durationValue = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("slidingSchedule")
  private Boolean slidingSchedule = null;

  @SerializedName("transactionType")
  private String transactionType = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  @SerializedName("value")
  private Integer value = null;

  public BalanceLimit balanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
    return this;
  }

   /**
   * balance definition ID
   * @return balanceDefinitionId
  **/
  @ApiModelProperty(value = "balance definition ID")
  public String getBalanceDefinitionId() {
    return balanceDefinitionId;
  }

  public void setBalanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
  }

  public BalanceLimit constraintType(String constraintType) {
    this.constraintType = constraintType;
    return this;
  }

   /**
   * Defines the type of constraint (e.g., transaction-based or amount-based).
   * @return constraintType
  **/
  @ApiModelProperty(value = "Defines the type of constraint (e.g., transaction-based or amount-based).")
  public String getConstraintType() {
    return constraintType;
  }

  public void setConstraintType(String constraintType) {
    this.constraintType = constraintType;
  }

  public BalanceLimit createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Timestamp of when the balance limit was created.
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "Timestamp of when the balance limit was created.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public BalanceLimit durationUnit(String durationUnit) {
    this.durationUnit = durationUnit;
    return this;
  }

   /**
   * Time unit for the balance limit (day, week, month, year).
   * @return durationUnit
  **/
  @ApiModelProperty(value = "Time unit for the balance limit (day, week, month, year).")
  public String getDurationUnit() {
    return durationUnit;
  }

  public void setDurationUnit(String durationUnit) {
    this.durationUnit = durationUnit;
  }

  public BalanceLimit durationValue(Integer durationValue) {
    this.durationValue = durationValue;
    return this;
  }

   /**
   * Number of time units the balance limit applies to.
   * @return durationValue
  **/
  @ApiModelProperty(value = "Number of time units the balance limit applies to.")
  public Integer getDurationValue() {
    return durationValue;
  }

  public void setDurationValue(Integer durationValue) {
    this.durationValue = durationValue;
  }

  public BalanceLimit id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the balance limit.
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier for the balance limit.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BalanceLimit slidingSchedule(Boolean slidingSchedule) {
    this.slidingSchedule = slidingSchedule;
    return this;
  }

   /**
   * Indicates if the limit resets periodically based on a sliding schedule.
   * @return slidingSchedule
  **/
  @ApiModelProperty(value = "Indicates if the limit resets periodically based on a sliding schedule.")
  public Boolean isSlidingSchedule() {
    return slidingSchedule;
  }

  public void setSlidingSchedule(Boolean slidingSchedule) {
    this.slidingSchedule = slidingSchedule;
  }

  public BalanceLimit transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Specifies whether the limit applies to credit or debit transactions.
   * @return transactionType
  **/
  @ApiModelProperty(value = "Specifies whether the limit applies to credit or debit transactions.")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }

  public BalanceLimit updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Timestamp of the last update to the balance limit.
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "Timestamp of the last update to the balance limit.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public BalanceLimit value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * The maximum allowed value for the defined constraint.
   * @return value
  **/
  @ApiModelProperty(value = "The maximum allowed value for the defined constraint.")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    BalanceLimit balanceLimit = (BalanceLimit) o;
    return ObjectUtils.equals(this.balanceDefinitionId, balanceLimit.balanceDefinitionId) &&
    ObjectUtils.equals(this.constraintType, balanceLimit.constraintType) &&
    ObjectUtils.equals(this.createdAt, balanceLimit.createdAt) &&
    ObjectUtils.equals(this.durationUnit, balanceLimit.durationUnit) &&
    ObjectUtils.equals(this.durationValue, balanceLimit.durationValue) &&
    ObjectUtils.equals(this.id, balanceLimit.id) &&
    ObjectUtils.equals(this.slidingSchedule, balanceLimit.slidingSchedule) &&
    ObjectUtils.equals(this.transactionType, balanceLimit.transactionType) &&
    ObjectUtils.equals(this.updatedAt, balanceLimit.updatedAt) &&
    ObjectUtils.equals(this.value, balanceLimit.value);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(balanceDefinitionId, constraintType, createdAt, durationUnit, durationValue, id, slidingSchedule, transactionType, updatedAt, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceLimit {\n");
    
    sb.append("    balanceDefinitionId: ").append(toIndentedString(balanceDefinitionId)).append("\n");
    sb.append("    constraintType: ").append(toIndentedString(constraintType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    durationUnit: ").append(toIndentedString(durationUnit)).append("\n");
    sb.append("    durationValue: ").append(toIndentedString(durationValue)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slidingSchedule: ").append(toIndentedString(slidingSchedule)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

