/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Represents an order linked to a balance definition, including amount, due date, and transaction details.
 */
@ApiModel(description = "Represents an order linked to a balance definition, including amount, due date, and transaction details.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class BalanceOrder {
  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("balanceDefinitionId")
  private String balanceDefinitionId = null;

  @SerializedName("contactId")
  private Integer contactId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("dueAt")
  private String dueAt = null;

  @SerializedName("expiresAt")
  private String expiresAt = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  @SerializedName("meta")
  private Object meta = null;

  @SerializedName("processedAt")
  private String processedAt = null;

  @SerializedName("transactionid")
  private String transactionid = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public BalanceOrder amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Order amount (must not be zero).
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "Order amount (must not be zero).")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public BalanceOrder balanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
    return this;
  }

   /**
   * Optional unique identifier (UUID) of the associated balance definition.
   * @return balanceDefinitionId
  **/
  @ApiModelProperty(value = "Optional unique identifier (UUID) of the associated balance definition.")
  public String getBalanceDefinitionId() {
    return balanceDefinitionId;
  }

  public void setBalanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
  }

  public BalanceOrder contactId(Integer contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Unique identifier of the contact placing the order (must be ≥ 1).
   * minimum: 1
   * @return contactId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of the contact placing the order (must be ≥ 1).")
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(Integer contactId) {
    this.contactId = contactId;
  }

  public BalanceOrder createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * RFC3339 timestamp indicating when the order was created.
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "RFC3339 timestamp indicating when the order was created.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public BalanceOrder dueAt(String dueAt) {
    this.dueAt = dueAt;
    return this;
  }

   /**
   * RFC3339 timestamp specifying when the order is due in the future.
   * @return dueAt
  **/
  @ApiModelProperty(required = true, value = "RFC3339 timestamp specifying when the order is due in the future.")
  public String getDueAt() {
    return dueAt;
  }

  public void setDueAt(String dueAt) {
    this.dueAt = dueAt;
  }

  public BalanceOrder expiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Optional RFC3339 timestamp defining order expiration in the future.
   * @return expiresAt
  **/
  @ApiModelProperty(value = "Optional RFC3339 timestamp defining order expiration in the future.")
  public String getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(String expiresAt) {
    this.expiresAt = expiresAt;
  }

  public BalanceOrder id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the balance order.
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier for the balance order.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BalanceOrder loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Unique identifier of the loyalty program associated with the order.
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of the loyalty program associated with the order.")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }

  public BalanceOrder meta(Object meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Optional metadata associated with the order.
   * @return meta
  **/
  @ApiModelProperty(value = "Optional metadata associated with the order.")
  public Object getMeta() {
    return meta;
  }

  public void setMeta(Object meta) {
    this.meta = meta;
  }

  public BalanceOrder processedAt(String processedAt) {
    this.processedAt = processedAt;
    return this;
  }

   /**
   * Optional RFC3339 timestamp indicating when the order was processed.
   * @return processedAt
  **/
  @ApiModelProperty(value = "Optional RFC3339 timestamp indicating when the order was processed.")
  public String getProcessedAt() {
    return processedAt;
  }

  public void setProcessedAt(String processedAt) {
    this.processedAt = processedAt;
  }

  public BalanceOrder transactionid(String transactionid) {
    this.transactionid = transactionid;
    return this;
  }

   /**
   * Optional reference to the associated transaction ID.
   * @return transactionid
  **/
  @ApiModelProperty(value = "Optional reference to the associated transaction ID.")
  public String getTransactionid() {
    return transactionid;
  }

  public void setTransactionid(String transactionid) {
    this.transactionid = transactionid;
  }

  public BalanceOrder updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * RFC3339 timestamp indicating the last update to the order.
   * @return updatedAt
  **/
  @ApiModelProperty(required = true, value = "RFC3339 timestamp indicating the last update to the order.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    BalanceOrder balanceOrder = (BalanceOrder) o;
    return ObjectUtils.equals(this.amount, balanceOrder.amount) &&
    ObjectUtils.equals(this.balanceDefinitionId, balanceOrder.balanceDefinitionId) &&
    ObjectUtils.equals(this.contactId, balanceOrder.contactId) &&
    ObjectUtils.equals(this.createdAt, balanceOrder.createdAt) &&
    ObjectUtils.equals(this.dueAt, balanceOrder.dueAt) &&
    ObjectUtils.equals(this.expiresAt, balanceOrder.expiresAt) &&
    ObjectUtils.equals(this.id, balanceOrder.id) &&
    ObjectUtils.equals(this.loyaltyProgramId, balanceOrder.loyaltyProgramId) &&
    ObjectUtils.equals(this.meta, balanceOrder.meta) &&
    ObjectUtils.equals(this.processedAt, balanceOrder.processedAt) &&
    ObjectUtils.equals(this.transactionid, balanceOrder.transactionid) &&
    ObjectUtils.equals(this.updatedAt, balanceOrder.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(amount, balanceDefinitionId, contactId, createdAt, dueAt, expiresAt, id, loyaltyProgramId, meta, processedAt, transactionid, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceOrder {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    balanceDefinitionId: ").append(toIndentedString(balanceDefinitionId)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    dueAt: ").append(toIndentedString(dueAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    processedAt: ").append(toIndentedString(processedAt)).append("\n");
    sb.append("    transactionid: ").append(toIndentedString(transactionid)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

