/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import brevoModel.BalanceDataPerContact;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ContactBalancesResp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class ContactBalancesResp {
  @SerializedName("balanceDefinitionId")
  private String balanceDefinitionId = null;

  @SerializedName("balances")
  private List<BalanceDataPerContact> balances = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  public ContactBalancesResp balanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
    return this;
  }

   /**
   * Get balanceDefinitionId
   * @return balanceDefinitionId
  **/
  @ApiModelProperty(value = "")
  public String getBalanceDefinitionId() {
    return balanceDefinitionId;
  }

  public void setBalanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
  }

  public ContactBalancesResp balances(List<BalanceDataPerContact> balances) {
    this.balances = balances;
    return this;
  }

  public ContactBalancesResp addBalancesItem(BalanceDataPerContact balancesItem) {
    if (this.balances == null) {
      this.balances = new ArrayList<BalanceDataPerContact>();
    }
    this.balances.add(balancesItem);
    return this;
  }

   /**
   * Get balances
   * @return balances
  **/
  @ApiModelProperty(value = "")
  public List<BalanceDataPerContact> getBalances() {
    return balances;
  }

  public void setBalances(List<BalanceDataPerContact> balances) {
    this.balances = balances;
  }

  public ContactBalancesResp count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public ContactBalancesResp loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Get loyaltyProgramId
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    ContactBalancesResp contactBalancesResp = (ContactBalancesResp) o;
    return ObjectUtils.equals(this.balanceDefinitionId, contactBalancesResp.balanceDefinitionId) &&
    ObjectUtils.equals(this.balances, contactBalancesResp.balances) &&
    ObjectUtils.equals(this.count, contactBalancesResp.count) &&
    ObjectUtils.equals(this.loyaltyProgramId, contactBalancesResp.loyaltyProgramId);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(balanceDefinitionId, balances, count, loyaltyProgramId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactBalancesResp {\n");
    
    sb.append("    balanceDefinitionId: ").append(toIndentedString(balanceDefinitionId)).append("\n");
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

