/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetAccountActivityLogs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class GetAccountActivityLogs {
  @SerializedName("action")
  private String action = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("user_email")
  private String userEmail = null;

  @SerializedName("user_ip")
  private String userIp = null;

  @SerializedName("user_agent")
  private String userAgent = null;

  public GetAccountActivityLogs action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Type of activity in the account.
   * @return action
  **/
  @ApiModelProperty(example = "login-success", required = true, value = "Type of activity in the account.")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public GetAccountActivityLogs date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Time of the activity.
   * @return date
  **/
  @ApiModelProperty(example = "2023-03-27T16:30:00Z", required = true, value = "Time of the activity.")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public GetAccountActivityLogs userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Email address of the user who performed activity in the account.
   * @return userEmail
  **/
  @ApiModelProperty(example = "test@mycompany.com", required = true, value = "Email address of the user who performed activity in the account.")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public GetAccountActivityLogs userIp(String userIp) {
    this.userIp = userIp;
    return this;
  }

   /**
   * IP address of the user who performed activity in the account.
   * @return userIp
  **/
  @ApiModelProperty(example = "192.158.1.38", required = true, value = "IP address of the user who performed activity in the account.")
  public String getUserIp() {
    return userIp;
  }

  public void setUserIp(String userIp) {
    this.userIp = userIp;
  }

  public GetAccountActivityLogs userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

   /**
   * Browser details of the user who performed the activity.
   * @return userAgent
  **/
  @ApiModelProperty(example = "Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us)", required = true, value = "Browser details of the user who performed the activity.")
  public String getUserAgent() {
    return userAgent;
  }

  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    GetAccountActivityLogs getAccountActivityLogs = (GetAccountActivityLogs) o;
    return ObjectUtils.equals(this.action, getAccountActivityLogs.action) &&
    ObjectUtils.equals(this.date, getAccountActivityLogs.date) &&
    ObjectUtils.equals(this.userEmail, getAccountActivityLogs.userEmail) &&
    ObjectUtils.equals(this.userIp, getAccountActivityLogs.userIp) &&
    ObjectUtils.equals(this.userAgent, getAccountActivityLogs.userAgent);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(action, date, userEmail, userIp, userAgent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAccountActivityLogs {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userIp: ").append(toIndentedString(userIp)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

