/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Privileges given to the user
 */
@ApiModel(description = "Privileges given to the user")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class InviteuserPrivileges {
  /**
   * Feature name
   */
  @JsonAdapter(FeatureEnum.Adapter.class)
  public enum FeatureEnum {
    EMAIL_CAMPAIGNS("email_campaigns"),
    
    SMS_CAMPAIGNS("sms_campaigns"),
    
    CONTACTS("contacts"),
    
    TEMPLATES("templates"),
    
    WORKFLOWS("workflows"),
    
    LANDING_PAGES("landing_pages"),
    
    TRANSACTIONAL_EMAILS("transactional_emails"),
    
    SMTP_API("smtp_api"),
    
    USER_MANAGEMENT("user_management"),
    
    SALES_PLATFORM("sales_platform"),
    
    PHONE("phone"),
    
    CONVERSATIONS("conversations"),
    
    SENDERS_DOMAINS_DEDICATED_IPS("senders_domains_dedicated_ips"),
    
    PUSH_NOTIFICATIONS("push_notifications");

    private String value;

    FeatureEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FeatureEnum fromValue(String text) {
      for (FeatureEnum b : FeatureEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FeatureEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FeatureEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FeatureEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FeatureEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("feature")
  private FeatureEnum feature = null;

  /**
   * Gets or Sets permissions
   */
  @JsonAdapter(PermissionsEnum.Adapter.class)
  public enum PermissionsEnum {
    CREATE_EDIT_DELETE("create_edit_delete"),
    
    SEND_SCHEDULE_SUSPEND("send_schedule_suspend"),
    
    VIEW("view"),
    
    IMPORT("import"),
    
    EXPORT("export"),
    
    LIST_AND_ATTRIBUTES("list_and_attributes"),
    
    FORMS("forms"),
    
    ACTIVATE_DEACTIVATE("activate_deactivate"),
    
    ACTIVATE_DEACTIVATE_PAUSE("activate_deactivate_pause"),
    
    SETTINGS("settings"),
    
    SCHEDULE_PAUSE("schedule_pause"),
    
    ALL("all"),
    
    LOGS("logs"),
    
    ACCESS("access"),
    
    ASSIGN("assign"),
    
    CONFIGURE("configure"),
    
    CREATE_EDIT_DEALS("create_edit_deals"),
    
    DELETE_DEALS("delete_deals"),
    
    MANAGE_OTHERS_DEALS_TASKS("manage_others_deals_tasks"),
    
    MANAGE_OWNED_COMPANIES("manage_owned_companies"),
    
    MANAGE_OTHERS_COMPANIES("manage_others_companies"),
    
    REPORTS("reports"),
    
    SENDERS_MANAGEMENT("senders_management"),
    
    DOMAINS_MANAGEMENT("domains_management"),
    
    DEDICATED_IPS_MANAGEMENT("dedicated_ips_management"),
    
    SEND("send"),
    
    SMTP("smtp"),
    
    API_KEYS("api_keys"),
    
    AUTHORIZED_IPS("authorized_ips"),
    
    NONE("none");

    private String value;

    PermissionsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PermissionsEnum fromValue(String text) {
      for (PermissionsEnum b : PermissionsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PermissionsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PermissionsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PermissionsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PermissionsEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("permissions")
  private List<PermissionsEnum> permissions = null;

  public InviteuserPrivileges feature(FeatureEnum feature) {
    this.feature = feature;
    return this;
  }

   /**
   * Feature name
   * @return feature
  **/
  @ApiModelProperty(example = "email_campaigns", value = "Feature name")
  public FeatureEnum getFeature() {
    return feature;
  }

  public void setFeature(FeatureEnum feature) {
    this.feature = feature;
  }

  public InviteuserPrivileges permissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
    return this;
  }

  public InviteuserPrivileges addPermissionsItem(PermissionsEnum permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<PermissionsEnum>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Permissions for a given feature
   * @return permissions
  **/
  @ApiModelProperty(value = "Permissions for a given feature")
  public List<PermissionsEnum> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<PermissionsEnum> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    InviteuserPrivileges inviteuserPrivileges = (InviteuserPrivileges) o;
    return ObjectUtils.equals(this.feature, inviteuserPrivileges.feature) &&
    ObjectUtils.equals(this.permissions, inviteuserPrivileges.permissions);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(feature, permissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InviteuserPrivileges {\n");
    
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

