/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LoyaltyProgramValidationError
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class LoyaltyProgramValidationError {
  @SerializedName("path")
  private String path = null;

  @SerializedName("rule")
  private String rule = null;

  @SerializedName("error")
  private String error = null;

  public LoyaltyProgramValidationError path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Path of data that failed validation
   * @return path
  **/
  @ApiModelProperty(value = "Path of data that failed validation")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public LoyaltyProgramValidationError rule(String rule) {
    this.rule = rule;
    return this;
  }

   /**
   * Rule that failed validation
   * @return rule
  **/
  @ApiModelProperty(value = "Rule that failed validation")
  public String getRule() {
    return rule;
  }

  public void setRule(String rule) {
    this.rule = rule;
  }

  public LoyaltyProgramValidationError error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Validation error message
   * @return error
  **/
  @ApiModelProperty(value = "Validation error message")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    LoyaltyProgramValidationError loyaltyProgramValidationError = (LoyaltyProgramValidationError) o;
    return ObjectUtils.equals(this.path, loyaltyProgramValidationError.path) &&
    ObjectUtils.equals(this.rule, loyaltyProgramValidationError.rule) &&
    ObjectUtils.equals(this.error, loyaltyProgramValidationError.error);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(path, rule, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltyProgramValidationError {\n");
    
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

