/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * LoyaltyProgram
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class LoyaltyProgram {
  @SerializedName("codeCount")
  private Integer codeCount = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("documentId")
  private String documentId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("meta")
  private Map<String, Object> meta = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pattern")
  private String pattern = null;

  /**
   * Loyalty Program state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    INACTIVE("inactive"),
    
    ACTIVE("active");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("subscriptionGeneratorId")
  private String subscriptionGeneratorId = null;

  @SerializedName("subscriptionPoolId")
  private String subscriptionPoolId = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public LoyaltyProgram codeCount(Integer codeCount) {
    this.codeCount = codeCount;
    return this;
  }

   /**
   * Loyalty Program code count
   * @return codeCount
  **/
  @ApiModelProperty(value = "Loyalty Program code count")
  public Integer getCodeCount() {
    return codeCount;
  }

  public void setCodeCount(Integer codeCount) {
    this.codeCount = codeCount;
  }

  public LoyaltyProgram createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Loyalty Program creation date
   * @return createdAt
  **/
  @ApiModelProperty(value = "Loyalty Program creation date")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public LoyaltyProgram description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Loyalty Program description
   * @return description
  **/
  @ApiModelProperty(value = "Loyalty Program description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LoyaltyProgram documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * string
   * @return documentId
  **/
  @ApiModelProperty(value = "string")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public LoyaltyProgram id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Loyalty Program ID
   * @return id
  **/
  @ApiModelProperty(value = "Loyalty Program ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LoyaltyProgram meta(Map<String, Object> meta) {
    this.meta = meta;
    return this;
  }

  public LoyaltyProgram putMetaItem(String key, Object metaItem) {
    if (this.meta == null) {
      this.meta = new HashMap<String, Object>();
    }
    this.meta.put(key, metaItem);
    return this;
  }

   /**
   * Loyalty Program meta data
   * @return meta
  **/
  @ApiModelProperty(value = "Loyalty Program meta data")
  public Map<String, Object> getMeta() {
    return meta;
  }

  public void setMeta(Map<String, Object> meta) {
    this.meta = meta;
  }

  public LoyaltyProgram name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Loyalty Program name
   * @return name
  **/
  @ApiModelProperty(value = "Loyalty Program name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LoyaltyProgram pattern(String pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * string
   * @return pattern
  **/
  @ApiModelProperty(value = "string")
  public String getPattern() {
    return pattern;
  }

  public void setPattern(String pattern) {
    this.pattern = pattern;
  }

  public LoyaltyProgram state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Loyalty Program state
   * @return state
  **/
  @ApiModelProperty(value = "Loyalty Program state")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public LoyaltyProgram subscriptionGeneratorId(String subscriptionGeneratorId) {
    this.subscriptionGeneratorId = subscriptionGeneratorId;
    return this;
  }

   /**
   * Loyalty Program subscription generator ID
   * @return subscriptionGeneratorId
  **/
  @ApiModelProperty(value = "Loyalty Program subscription generator ID")
  public String getSubscriptionGeneratorId() {
    return subscriptionGeneratorId;
  }

  public void setSubscriptionGeneratorId(String subscriptionGeneratorId) {
    this.subscriptionGeneratorId = subscriptionGeneratorId;
  }

  public LoyaltyProgram subscriptionPoolId(String subscriptionPoolId) {
    this.subscriptionPoolId = subscriptionPoolId;
    return this;
  }

   /**
   * Loyalty Program subscription pool ID
   * @return subscriptionPoolId
  **/
  @ApiModelProperty(value = "Loyalty Program subscription pool ID")
  public String getSubscriptionPoolId() {
    return subscriptionPoolId;
  }

  public void setSubscriptionPoolId(String subscriptionPoolId) {
    this.subscriptionPoolId = subscriptionPoolId;
  }

  public LoyaltyProgram updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Loyalty Program last modification date
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Loyalty Program last modification date")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    LoyaltyProgram loyaltyProgram = (LoyaltyProgram) o;
    return ObjectUtils.equals(this.codeCount, loyaltyProgram.codeCount) &&
    ObjectUtils.equals(this.createdAt, loyaltyProgram.createdAt) &&
    ObjectUtils.equals(this.description, loyaltyProgram.description) &&
    ObjectUtils.equals(this.documentId, loyaltyProgram.documentId) &&
    ObjectUtils.equals(this.id, loyaltyProgram.id) &&
    ObjectUtils.equals(this.meta, loyaltyProgram.meta) &&
    ObjectUtils.equals(this.name, loyaltyProgram.name) &&
    ObjectUtils.equals(this.pattern, loyaltyProgram.pattern) &&
    ObjectUtils.equals(this.state, loyaltyProgram.state) &&
    ObjectUtils.equals(this.subscriptionGeneratorId, loyaltyProgram.subscriptionGeneratorId) &&
    ObjectUtils.equals(this.subscriptionPoolId, loyaltyProgram.subscriptionPoolId) &&
    ObjectUtils.equals(this.updatedAt, loyaltyProgram.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(codeCount, createdAt, description, documentId, id, meta, name, pattern, state, subscriptionGeneratorId, subscriptionPoolId, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltyProgram {\n");
    
    sb.append("    codeCount: ").append(toIndentedString(codeCount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    subscriptionGeneratorId: ").append(toIndentedString(subscriptionGeneratorId)).append("\n");
    sb.append("    subscriptionPoolId: ").append(toIndentedString(subscriptionPoolId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

