/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * MainRedeem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class MainRedeem {
  @SerializedName("cancelledAt")
  private OffsetDateTime cancelledAt = null;

  @SerializedName("completedAt")
  private OffsetDateTime completedAt = null;

  @SerializedName("contactId")
  private Long contactId = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("debitTransactionId")
  private UUID debitTransactionId = null;

  @SerializedName("expiresAt")
  private OffsetDateTime expiresAt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("loyaltyProgramId")
  private UUID loyaltyProgramId = null;

  @SerializedName("meta")
  private Map<String, Object> meta = null;

  @SerializedName("rejectReason")
  private String rejectReason = null;

  @SerializedName("rejectedAt")
  private OffsetDateTime rejectedAt = null;

  @SerializedName("rewardAttributionId")
  private UUID rewardAttributionId = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  public MainRedeem cancelledAt(OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
    return this;
  }

   /**
   * Timestamp when the redemption was cancelled
   * @return cancelledAt
  **/
  @ApiModelProperty(value = "Timestamp when the redemption was cancelled")
  public OffsetDateTime getCancelledAt() {
    return cancelledAt;
  }

  public void setCancelledAt(OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
  }

  public MainRedeem completedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

   /**
   * Timestamp when the redemption was completed
   * @return completedAt
  **/
  @ApiModelProperty(value = "Timestamp when the redemption was completed")
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }

  public MainRedeem contactId(Long contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Unique identifier for the contact
   * @return contactId
  **/
  @ApiModelProperty(value = "Unique identifier for the contact")
  public Long getContactId() {
    return contactId;
  }

  public void setContactId(Long contactId) {
    this.contactId = contactId;
  }

  public MainRedeem createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Timestamp when the redemption was created
   * @return createdAt
  **/
  @ApiModelProperty(value = "Timestamp when the redemption was created")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public MainRedeem debitTransactionId(UUID debitTransactionId) {
    this.debitTransactionId = debitTransactionId;
    return this;
  }

   /**
   * Unique identifier for the debit transaction
   * @return debitTransactionId
  **/
  @ApiModelProperty(value = "Unique identifier for the debit transaction")
  public UUID getDebitTransactionId() {
    return debitTransactionId;
  }

  public void setDebitTransactionId(UUID debitTransactionId) {
    this.debitTransactionId = debitTransactionId;
  }

  public MainRedeem expiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Timestamp when the redemption expires
   * @return expiresAt
  **/
  @ApiModelProperty(value = "Timestamp when the redemption expires")
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  public MainRedeem id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the redemption
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier for the redemption")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public MainRedeem loyaltyProgramId(UUID loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Unique identifier for the loyalty program
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "Unique identifier for the loyalty program")
  public UUID getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(UUID loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }

  public MainRedeem meta(Map<String, Object> meta) {
    this.meta = meta;
    return this;
  }

  public MainRedeem putMetaItem(String key, Object metaItem) {
    if (this.meta == null) {
      this.meta = new HashMap<String, Object>();
    }
    this.meta.put(key, metaItem);
    return this;
  }

   /**
   * Additional metadata associated with the redemption
   * @return meta
  **/
  @ApiModelProperty(value = "Additional metadata associated with the redemption")
  public Map<String, Object> getMeta() {
    return meta;
  }

  public void setMeta(Map<String, Object> meta) {
    this.meta = meta;
  }

  public MainRedeem rejectReason(String rejectReason) {
    this.rejectReason = rejectReason;
    return this;
  }

   /**
   * Reason for rejection if the redemption was rejected
   * @return rejectReason
  **/
  @ApiModelProperty(value = "Reason for rejection if the redemption was rejected")
  public String getRejectReason() {
    return rejectReason;
  }

  public void setRejectReason(String rejectReason) {
    this.rejectReason = rejectReason;
  }

  public MainRedeem rejectedAt(OffsetDateTime rejectedAt) {
    this.rejectedAt = rejectedAt;
    return this;
  }

   /**
   * Timestamp when the redemption was rejected
   * @return rejectedAt
  **/
  @ApiModelProperty(value = "Timestamp when the redemption was rejected")
  public OffsetDateTime getRejectedAt() {
    return rejectedAt;
  }

  public void setRejectedAt(OffsetDateTime rejectedAt) {
    this.rejectedAt = rejectedAt;
  }

  public MainRedeem rewardAttributionId(UUID rewardAttributionId) {
    this.rewardAttributionId = rewardAttributionId;
    return this;
  }

   /**
   * Unique identifier for the reward attribution
   * @return rewardAttributionId
  **/
  @ApiModelProperty(value = "Unique identifier for the reward attribution")
  public UUID getRewardAttributionId() {
    return rewardAttributionId;
  }

  public void setRewardAttributionId(UUID rewardAttributionId) {
    this.rewardAttributionId = rewardAttributionId;
  }

  public MainRedeem status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Current status of the redemption
   * @return status
  **/
  @ApiModelProperty(value = "Current status of the redemption")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public MainRedeem updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Timestamp when the redemption was last updated
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Timestamp when the redemption was last updated")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MainRedeem mainRedeem = (MainRedeem) o;
    return ObjectUtils.equals(this.cancelledAt, mainRedeem.cancelledAt) &&
    ObjectUtils.equals(this.completedAt, mainRedeem.completedAt) &&
    ObjectUtils.equals(this.contactId, mainRedeem.contactId) &&
    ObjectUtils.equals(this.createdAt, mainRedeem.createdAt) &&
    ObjectUtils.equals(this.debitTransactionId, mainRedeem.debitTransactionId) &&
    ObjectUtils.equals(this.expiresAt, mainRedeem.expiresAt) &&
    ObjectUtils.equals(this.id, mainRedeem.id) &&
    ObjectUtils.equals(this.loyaltyProgramId, mainRedeem.loyaltyProgramId) &&
    ObjectUtils.equals(this.meta, mainRedeem.meta) &&
    ObjectUtils.equals(this.rejectReason, mainRedeem.rejectReason) &&
    ObjectUtils.equals(this.rejectedAt, mainRedeem.rejectedAt) &&
    ObjectUtils.equals(this.rewardAttributionId, mainRedeem.rewardAttributionId) &&
    ObjectUtils.equals(this.status, mainRedeem.status) &&
    ObjectUtils.equals(this.updatedAt, mainRedeem.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(cancelledAt, completedAt, contactId, createdAt, debitTransactionId, expiresAt, id, loyaltyProgramId, meta, rejectReason, rejectedAt, rewardAttributionId, status, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainRedeem {\n");
    
    sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    debitTransactionId: ").append(toIndentedString(debitTransactionId)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    rejectedAt: ").append(toIndentedString(rejectedAt)).append("\n");
    sb.append("    rewardAttributionId: ").append(toIndentedString(rewardAttributionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

