/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import brevoModel.MainRuleConditionResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MainRuleConditionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class MainRuleConditionResponse {
  @SerializedName("and")
  private List<MainRuleConditionResponse> and = null;

  @SerializedName("lhs")
  private Object lhs = null;

  @SerializedName("op")
  private String op = null;

  @SerializedName("or")
  private List<MainRuleConditionResponse> or = null;

  @SerializedName("rhs")
  private Object rhs = null;

  public MainRuleConditionResponse and(List<MainRuleConditionResponse> and) {
    this.and = and;
    return this;
  }

  public MainRuleConditionResponse addAndItem(MainRuleConditionResponse andItem) {
    if (this.and == null) {
      this.and = new ArrayList<MainRuleConditionResponse>();
    }
    this.and.add(andItem);
    return this;
  }

   /**
   * Metric to indicate AND between rules
   * @return and
  **/
  @ApiModelProperty(value = "Metric to indicate AND between rules")
  public List<MainRuleConditionResponse> getAnd() {
    return and;
  }

  public void setAnd(List<MainRuleConditionResponse> and) {
    this.and = and;
  }

  public MainRuleConditionResponse lhs(Object lhs) {
    this.lhs = lhs;
    return this;
  }

   /**
   * Conditon of the rule
   * @return lhs
  **/
  @ApiModelProperty(value = "Conditon of the rule")
  public Object getLhs() {
    return lhs;
  }

  public void setLhs(Object lhs) {
    this.lhs = lhs;
  }

  public MainRuleConditionResponse op(String op) {
    this.op = op;
    return this;
  }

   /**
   * Selected operator for the rule
   * @return op
  **/
  @ApiModelProperty(value = "Selected operator for the rule")
  public String getOp() {
    return op;
  }

  public void setOp(String op) {
    this.op = op;
  }

  public MainRuleConditionResponse or(List<MainRuleConditionResponse> or) {
    this.or = or;
    return this;
  }

  public MainRuleConditionResponse addOrItem(MainRuleConditionResponse orItem) {
    if (this.or == null) {
      this.or = new ArrayList<MainRuleConditionResponse>();
    }
    this.or.add(orItem);
    return this;
  }

   /**
   * Metric to indicate OR between rules
   * @return or
  **/
  @ApiModelProperty(value = "Metric to indicate OR between rules")
  public List<MainRuleConditionResponse> getOr() {
    return or;
  }

  public void setOr(List<MainRuleConditionResponse> or) {
    this.or = or;
  }

  public MainRuleConditionResponse rhs(Object rhs) {
    this.rhs = rhs;
    return this;
  }

   /**
   * Action of the rule
   * @return rhs
  **/
  @ApiModelProperty(value = "Action of the rule")
  public Object getRhs() {
    return rhs;
  }

  public void setRhs(Object rhs) {
    this.rhs = rhs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MainRuleConditionResponse mainRuleConditionResponse = (MainRuleConditionResponse) o;
    return ObjectUtils.equals(this.and, mainRuleConditionResponse.and) &&
    ObjectUtils.equals(this.lhs, mainRuleConditionResponse.lhs) &&
    ObjectUtils.equals(this.op, mainRuleConditionResponse.op) &&
    ObjectUtils.equals(this.or, mainRuleConditionResponse.or) &&
    ObjectUtils.equals(this.rhs, mainRuleConditionResponse.rhs);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(and, lhs, op, or, rhs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainRuleConditionResponse {\n");
    
    sb.append("    and: ").append(toIndentedString(and)).append("\n");
    sb.append("    lhs: ").append(toIndentedString(lhs)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    or: ").append(toIndentedString(or)).append("\n");
    sb.append("    rhs: ").append(toIndentedString(rhs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

