/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * MainProductPayload
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class MainProductPayload {
  @SerializedName("category")
  private List<String> category = null;

  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("productId")
  private String productId = null;

  @SerializedName("quantity")
  private BigDecimal quantity = null;

  @SerializedName("variantId")
  private String variantId = null;

  public MainProductPayload category(List<String> category) {
    this.category = category;
    return this;
  }

  public MainProductPayload addCategoryItem(String categoryItem) {
    if (this.category == null) {
      this.category = new ArrayList<String>();
    }
    this.category.add(categoryItem);
    return this;
  }

   /**
   * List of categories the product belongs to
   * @return category
  **/
  @ApiModelProperty(value = "List of categories the product belongs to")
  public List<String> getCategory() {
    return category;
  }

  public void setCategory(List<String> category) {
    this.category = category;
  }

  public MainProductPayload price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Price of the product
   * @return price
  **/
  @ApiModelProperty(value = "Price of the product")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public MainProductPayload productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Unique identifier for the product
   * @return productId
  **/
  @ApiModelProperty(value = "Unique identifier for the product")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public MainProductPayload quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity of the product
   * @return quantity
  **/
  @ApiModelProperty(value = "Quantity of the product")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public MainProductPayload variantId(String variantId) {
    this.variantId = variantId;
    return this;
  }

   /**
   * Identifier for the product variant
   * @return variantId
  **/
  @ApiModelProperty(value = "Identifier for the product variant")
  public String getVariantId() {
    return variantId;
  }

  public void setVariantId(String variantId) {
    this.variantId = variantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MainProductPayload mainProductPayload = (MainProductPayload) o;
    return ObjectUtils.equals(this.category, mainProductPayload.category) &&
    ObjectUtils.equals(this.price, mainProductPayload.price) &&
    ObjectUtils.equals(this.productId, mainProductPayload.productId) &&
    ObjectUtils.equals(this.quantity, mainProductPayload.quantity) &&
    ObjectUtils.equals(this.variantId, mainProductPayload.variantId);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(category, price, productId, quantity, variantId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainProductPayload {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    variantId: ").append(toIndentedString(variantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

