/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SubscriptionMember
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class SubscriptionMember {
  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("memberContactIds")
  private List<Integer> memberContactIds = null;

  @SerializedName("organizationId")
  private Integer organizationId = null;

  @SerializedName("ownerContactId")
  private Integer ownerContactId = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public SubscriptionMember createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Timestamp when the subscription member was created.
   * @return createdAt
  **/
  @ApiModelProperty(value = "Timestamp when the subscription member was created.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public SubscriptionMember memberContactIds(List<Integer> memberContactIds) {
    this.memberContactIds = memberContactIds;
    return this;
  }

  public SubscriptionMember addMemberContactIdsItem(Integer memberContactIdsItem) {
    if (this.memberContactIds == null) {
      this.memberContactIds = new ArrayList<Integer>();
    }
    this.memberContactIds.add(memberContactIdsItem);
    return this;
  }

   /**
   * List of unique member contact IDs.
   * @return memberContactIds
  **/
  @ApiModelProperty(value = "List of unique member contact IDs.")
  public List<Integer> getMemberContactIds() {
    return memberContactIds;
  }

  public void setMemberContactIds(List<Integer> memberContactIds) {
    this.memberContactIds = memberContactIds;
  }

  public SubscriptionMember organizationId(Integer organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Unique identifier of the organization.
   * @return organizationId
  **/
  @ApiModelProperty(value = "Unique identifier of the organization.")
  public Integer getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Integer organizationId) {
    this.organizationId = organizationId;
  }

  public SubscriptionMember ownerContactId(Integer ownerContactId) {
    this.ownerContactId = ownerContactId;
    return this;
  }

   /**
   * Unique identifier of the subscription owner.
   * @return ownerContactId
  **/
  @ApiModelProperty(value = "Unique identifier of the subscription owner.")
  public Integer getOwnerContactId() {
    return ownerContactId;
  }

  public void setOwnerContactId(Integer ownerContactId) {
    this.ownerContactId = ownerContactId;
  }

  public SubscriptionMember updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Timestamp when the subscription member was last updated.
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Timestamp when the subscription member was last updated.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    SubscriptionMember subscriptionMember = (SubscriptionMember) o;
    return ObjectUtils.equals(this.createdAt, subscriptionMember.createdAt) &&
    ObjectUtils.equals(this.memberContactIds, subscriptionMember.memberContactIds) &&
    ObjectUtils.equals(this.organizationId, subscriptionMember.organizationId) &&
    ObjectUtils.equals(this.ownerContactId, subscriptionMember.ownerContactId) &&
    ObjectUtils.equals(this.updatedAt, subscriptionMember.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(createdAt, memberContactIds, organizationId, ownerContactId, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionMember {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    memberContactIds: ").append(toIndentedString(memberContactIds)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    ownerContactId: ").append(toIndentedString(ownerContactId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

