/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import brevoModel.SubscriptionAggregateBalance;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SubscriptionBalances
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class SubscriptionBalances {
  @SerializedName("balances")
  private List<SubscriptionAggregateBalance> balances = null;

  @SerializedName("contactId")
  private Integer contactId = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  public SubscriptionBalances balances(List<SubscriptionAggregateBalance> balances) {
    this.balances = balances;
    return this;
  }

  public SubscriptionBalances addBalancesItem(SubscriptionAggregateBalance balancesItem) {
    if (this.balances == null) {
      this.balances = new ArrayList<SubscriptionAggregateBalance>();
    }
    this.balances.add(balancesItem);
    return this;
  }

   /**
   * List of balance details associated with the contact.
   * @return balances
  **/
  @ApiModelProperty(value = "List of balance details associated with the contact.")
  public List<SubscriptionAggregateBalance> getBalances() {
    return balances;
  }

  public void setBalances(List<SubscriptionAggregateBalance> balances) {
    this.balances = balances;
  }

  public SubscriptionBalances contactId(Integer contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Unique identifier of the contact.
   * @return contactId
  **/
  @ApiModelProperty(value = "Unique identifier of the contact.")
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(Integer contactId) {
    this.contactId = contactId;
  }

  public SubscriptionBalances loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Unique identifier of the loyalty program.
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "Unique identifier of the loyalty program.")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    SubscriptionBalances subscriptionBalances = (SubscriptionBalances) o;
    return ObjectUtils.equals(this.balances, subscriptionBalances.balances) &&
    ObjectUtils.equals(this.contactId, subscriptionBalances.contactId) &&
    ObjectUtils.equals(this.loyaltyProgramId, subscriptionBalances.loyaltyProgramId);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(balances, contactId, loyaltyProgramId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionBalances {\n");
    
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

