/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SubscriptionTier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class SubscriptionTier {
  @SerializedName("contactId")
  private Integer contactId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("groupId")
  private String groupId = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  @SerializedName("meta")
  private Map<String, Object> meta = null;

  @SerializedName("tierId")
  private String tierId = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public SubscriptionTier contactId(Integer contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Unique identifier of the contact.
   * @return contactId
  **/
  @ApiModelProperty(value = "Unique identifier of the contact.")
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(Integer contactId) {
    this.contactId = contactId;
  }

  public SubscriptionTier createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Timestamp when the tier was assigned.
   * @return createdAt
  **/
  @ApiModelProperty(value = "Timestamp when the tier was assigned.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public SubscriptionTier groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Unique identifier of the group associated with the tier.
   * @return groupId
  **/
  @ApiModelProperty(value = "Unique identifier of the group associated with the tier.")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public SubscriptionTier loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Unique identifier of the loyalty program.
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "Unique identifier of the loyalty program.")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }

  public SubscriptionTier meta(Map<String, Object> meta) {
    this.meta = meta;
    return this;
  }

  public SubscriptionTier putMetaItem(String key, Object metaItem) {
    if (this.meta == null) {
      this.meta = new HashMap<String, Object>();
    }
    this.meta.put(key, metaItem);
    return this;
  }

   /**
   * Additional metadata related to the tier.
   * @return meta
  **/
  @ApiModelProperty(value = "Additional metadata related to the tier.")
  public Map<String, Object> getMeta() {
    return meta;
  }

  public void setMeta(Map<String, Object> meta) {
    this.meta = meta;
  }

  public SubscriptionTier tierId(String tierId) {
    this.tierId = tierId;
    return this;
  }

   /**
   * Unique identifier of the tier.
   * @return tierId
  **/
  @ApiModelProperty(value = "Unique identifier of the tier.")
  public String getTierId() {
    return tierId;
  }

  public void setTierId(String tierId) {
    this.tierId = tierId;
  }

  public SubscriptionTier updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Timestamp when the tier was last updated
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Timestamp when the tier was last updated")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    SubscriptionTier subscriptionTier = (SubscriptionTier) o;
    return ObjectUtils.equals(this.contactId, subscriptionTier.contactId) &&
    ObjectUtils.equals(this.createdAt, subscriptionTier.createdAt) &&
    ObjectUtils.equals(this.groupId, subscriptionTier.groupId) &&
    ObjectUtils.equals(this.loyaltyProgramId, subscriptionTier.loyaltyProgramId) &&
    ObjectUtils.equals(this.meta, subscriptionTier.meta) &&
    ObjectUtils.equals(this.tierId, subscriptionTier.tierId) &&
    ObjectUtils.equals(this.updatedAt, subscriptionTier.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(contactId, createdAt, groupId, loyaltyProgramId, meta, tierId, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionTier {\n");
    
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    tierId: ").append(toIndentedString(tierId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

