/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SubscriptionAttributedReward
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class SubscriptionAttributedReward {
  @SerializedName("code")
  private String code = null;

  @SerializedName("contactId")
  private Integer contactId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("expirationDate")
  private String expirationDate = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  @SerializedName("meta")
  private Map<String, Object> meta = null;

  @SerializedName("rewardId")
  private String rewardId = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public SubscriptionAttributedReward code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Reward code assigned to the contact.
   * @return code
  **/
  @ApiModelProperty(value = "Reward code assigned to the contact.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SubscriptionAttributedReward contactId(Integer contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Unique identifier of the contact.
   * @return contactId
  **/
  @ApiModelProperty(value = "Unique identifier of the contact.")
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(Integer contactId) {
    this.contactId = contactId;
  }

  public SubscriptionAttributedReward createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Timestamp when the reward was created.
   * @return createdAt
  **/
  @ApiModelProperty(value = "Timestamp when the reward was created.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public SubscriptionAttributedReward expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Expiration date of the reward.
   * @return expirationDate
  **/
  @ApiModelProperty(value = "Expiration date of the reward.")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public SubscriptionAttributedReward id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the reward.
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier of the reward.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SubscriptionAttributedReward loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Unique identifier of the loyalty program.
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "Unique identifier of the loyalty program.")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }

  public SubscriptionAttributedReward meta(Map<String, Object> meta) {
    this.meta = meta;
    return this;
  }

  public SubscriptionAttributedReward putMetaItem(String key, Object metaItem) {
    if (this.meta == null) {
      this.meta = new HashMap<String, Object>();
    }
    this.meta.put(key, metaItem);
    return this;
  }

   /**
   * Additional metadata related to the reward.
   * @return meta
  **/
  @ApiModelProperty(value = "Additional metadata related to the reward.")
  public Map<String, Object> getMeta() {
    return meta;
  }

  public void setMeta(Map<String, Object> meta) {
    this.meta = meta;
  }

  public SubscriptionAttributedReward rewardId(String rewardId) {
    this.rewardId = rewardId;
    return this;
  }

   /**
   * Unique identifier of the reward definition.
   * @return rewardId
  **/
  @ApiModelProperty(value = "Unique identifier of the reward definition.")
  public String getRewardId() {
    return rewardId;
  }

  public void setRewardId(String rewardId) {
    this.rewardId = rewardId;
  }

  public SubscriptionAttributedReward updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Timestamp when the reward was last updated.
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Timestamp when the reward was last updated.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    SubscriptionAttributedReward subscriptionAttributedReward = (SubscriptionAttributedReward) o;
    return ObjectUtils.equals(this.code, subscriptionAttributedReward.code) &&
    ObjectUtils.equals(this.contactId, subscriptionAttributedReward.contactId) &&
    ObjectUtils.equals(this.createdAt, subscriptionAttributedReward.createdAt) &&
    ObjectUtils.equals(this.expirationDate, subscriptionAttributedReward.expirationDate) &&
    ObjectUtils.equals(this.id, subscriptionAttributedReward.id) &&
    ObjectUtils.equals(this.loyaltyProgramId, subscriptionAttributedReward.loyaltyProgramId) &&
    ObjectUtils.equals(this.meta, subscriptionAttributedReward.meta) &&
    ObjectUtils.equals(this.rewardId, subscriptionAttributedReward.rewardId) &&
    ObjectUtils.equals(this.updatedAt, subscriptionAttributedReward.updatedAt);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(code, contactId, createdAt, expirationDate, id, loyaltyProgramId, meta, rewardId, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionAttributedReward {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    rewardId: ").append(toIndentedString(rewardId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

