/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import brevoModel.TierRequestAccessConditions;
import brevoModel.TierRequestTierRewards;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TierRequestPutPayload
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class TierRequestPutPayload {
  @SerializedName("name")
  private String name = null;

  @SerializedName("imageRef")
  private String imageRef = null;

  @SerializedName("accessConditions")
  private List<TierRequestAccessConditions> accessConditions = new ArrayList<TierRequestAccessConditions>();

  @SerializedName("tierRewards")
  private List<TierRequestTierRewards> tierRewards = new ArrayList<TierRequestTierRewards>();

  public TierRequestPutPayload name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the tier to be created
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the tier to be created")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TierRequestPutPayload imageRef(String imageRef) {
    this.imageRef = imageRef;
    return this;
  }

   /**
   * Image of the tier
   * @return imageRef
  **/
  @ApiModelProperty(value = "Image of the tier")
  public String getImageRef() {
    return imageRef;
  }

  public void setImageRef(String imageRef) {
    this.imageRef = imageRef;
  }

  public TierRequestPutPayload accessConditions(List<TierRequestAccessConditions> accessConditions) {
    this.accessConditions = accessConditions;
    return this;
  }

  public TierRequestPutPayload addAccessConditionsItem(TierRequestAccessConditions accessConditionsItem) {
    this.accessConditions.add(accessConditionsItem);
    return this;
  }

   /**
   * Get accessConditions
   * @return accessConditions
  **/
  @ApiModelProperty(required = true, value = "")
  public List<TierRequestAccessConditions> getAccessConditions() {
    return accessConditions;
  }

  public void setAccessConditions(List<TierRequestAccessConditions> accessConditions) {
    this.accessConditions = accessConditions;
  }

  public TierRequestPutPayload tierRewards(List<TierRequestTierRewards> tierRewards) {
    this.tierRewards = tierRewards;
    return this;
  }

  public TierRequestPutPayload addTierRewardsItem(TierRequestTierRewards tierRewardsItem) {
    this.tierRewards.add(tierRewardsItem);
    return this;
  }

   /**
   * Get tierRewards
   * @return tierRewards
  **/
  @ApiModelProperty(required = true, value = "")
  public List<TierRequestTierRewards> getTierRewards() {
    return tierRewards;
  }

  public void setTierRewards(List<TierRequestTierRewards> tierRewards) {
    this.tierRewards = tierRewards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    TierRequestPutPayload tierRequestPutPayload = (TierRequestPutPayload) o;
    return ObjectUtils.equals(this.name, tierRequestPutPayload.name) &&
    ObjectUtils.equals(this.imageRef, tierRequestPutPayload.imageRef) &&
    ObjectUtils.equals(this.accessConditions, tierRequestPutPayload.accessConditions) &&
    ObjectUtils.equals(this.tierRewards, tierRequestPutPayload.tierRewards);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(name, imageRef, accessConditions, tierRewards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TierRequestPutPayload {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    imageRef: ").append(toIndentedString(imageRef)).append("\n");
    sb.append("    accessConditions: ").append(toIndentedString(accessConditions)).append("\n");
    sb.append("    tierRewards: ").append(toIndentedString(tierRewards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

