/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import brevoModel.TransactionHistory;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Response containing transaction history details for a specific balance and contact.
 */
@ApiModel(description = "Response containing transaction history details for a specific balance and contact.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class TransactionHistoryResp {
  @SerializedName("balanceDefinitionId")
  private String balanceDefinitionId = null;

  @SerializedName("contactId")
  private Integer contactId = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("loyaltyProgramId")
  private String loyaltyProgramId = null;

  @SerializedName("transactionHistory")
  private List<TransactionHistory> transactionHistory = null;

  public TransactionHistoryResp balanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
    return this;
  }

   /**
   * Unique identifier of the associated balance definition.
   * @return balanceDefinitionId
  **/
  @ApiModelProperty(value = "Unique identifier of the associated balance definition.")
  public String getBalanceDefinitionId() {
    return balanceDefinitionId;
  }

  public void setBalanceDefinitionId(String balanceDefinitionId) {
    this.balanceDefinitionId = balanceDefinitionId;
  }

  public TransactionHistoryResp contactId(Integer contactId) {
    this.contactId = contactId;
    return this;
  }

   /**
   * Unique identifier of the contact related to the transactions.
   * @return contactId
  **/
  @ApiModelProperty(value = "Unique identifier of the contact related to the transactions.")
  public Integer getContactId() {
    return contactId;
  }

  public void setContactId(Integer contactId) {
    this.contactId = contactId;
  }

  public TransactionHistoryResp count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Total number of transactions in the history.
   * @return count
  **/
  @ApiModelProperty(value = "Total number of transactions in the history.")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public TransactionHistoryResp loyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
    return this;
  }

   /**
   * Unique identifier of the associated loyalty program.
   * @return loyaltyProgramId
  **/
  @ApiModelProperty(value = "Unique identifier of the associated loyalty program.")
  public String getLoyaltyProgramId() {
    return loyaltyProgramId;
  }

  public void setLoyaltyProgramId(String loyaltyProgramId) {
    this.loyaltyProgramId = loyaltyProgramId;
  }

  public TransactionHistoryResp transactionHistory(List<TransactionHistory> transactionHistory) {
    this.transactionHistory = transactionHistory;
    return this;
  }

  public TransactionHistoryResp addTransactionHistoryItem(TransactionHistory transactionHistoryItem) {
    if (this.transactionHistory == null) {
      this.transactionHistory = new ArrayList<TransactionHistory>();
    }
    this.transactionHistory.add(transactionHistoryItem);
    return this;
  }

   /**
   * List of past transactions associated with the balance.
   * @return transactionHistory
  **/
  @ApiModelProperty(value = "List of past transactions associated with the balance.")
  public List<TransactionHistory> getTransactionHistory() {
    return transactionHistory;
  }

  public void setTransactionHistory(List<TransactionHistory> transactionHistory) {
    this.transactionHistory = transactionHistory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    TransactionHistoryResp transactionHistoryResp = (TransactionHistoryResp) o;
    return ObjectUtils.equals(this.balanceDefinitionId, transactionHistoryResp.balanceDefinitionId) &&
    ObjectUtils.equals(this.contactId, transactionHistoryResp.contactId) &&
    ObjectUtils.equals(this.count, transactionHistoryResp.count) &&
    ObjectUtils.equals(this.loyaltyProgramId, transactionHistoryResp.loyaltyProgramId) &&
    ObjectUtils.equals(this.transactionHistory, transactionHistoryResp.transactionHistory);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(balanceDefinitionId, contactId, count, loyaltyProgramId, transactionHistory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionHistoryResp {\n");
    
    sb.append("    balanceDefinitionId: ").append(toIndentedString(balanceDefinitionId)).append("\n");
    sb.append("    contactId: ").append(toIndentedString(contactId)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    loyaltyProgramId: ").append(toIndentedString(loyaltyProgramId)).append("\n");
    sb.append("    transactionHistory: ").append(toIndentedString(transactionHistory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

