/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Payload for updating an existing balance limit, specifying constraints on transactions or amounts.
 */
@ApiModel(description = "Payload for updating an existing balance limit, specifying constraints on transactions or amounts.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-17T10:38:30.728+05:30")
public class UpdateBalanceLimitPayload {
  /**
   * Defines whether the limit applies to transaction count or amount.
   */
  @JsonAdapter(ConstraintTypeEnum.Adapter.class)
  public enum ConstraintTypeEnum {
    TRANSACTION("transaction"),
    
    AMOUNT("amount");

    private String value;

    ConstraintTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConstraintTypeEnum fromValue(String text) {
      for (ConstraintTypeEnum b : ConstraintTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ConstraintTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConstraintTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConstraintTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ConstraintTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("constraintType")
  private ConstraintTypeEnum constraintType = null;

  /**
   * Unit of time for which the limit is applicable.
   */
  @JsonAdapter(DurationUnitEnum.Adapter.class)
  public enum DurationUnitEnum {
    DAY("day"),
    
    WEEK("week"),
    
    MONTH("month"),
    
    YEAR("year");

    private String value;

    DurationUnitEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DurationUnitEnum fromValue(String text) {
      for (DurationUnitEnum b : DurationUnitEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DurationUnitEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DurationUnitEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DurationUnitEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DurationUnitEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("durationUnit")
  private DurationUnitEnum durationUnit = null;

  @SerializedName("durationValue")
  private Integer durationValue = null;

  @SerializedName("slidingSchedule")
  private Boolean slidingSchedule = null;

  /**
   * Specifies whether the limit applies to credit or debit transactions.
   */
  @JsonAdapter(TransactionTypeEnum.Adapter.class)
  public enum TransactionTypeEnum {
    CREDIT("credit"),
    
    DEBIT("debit");

    private String value;

    TransactionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TransactionTypeEnum fromValue(String text) {
      for (TransactionTypeEnum b : TransactionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TransactionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TransactionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TransactionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TransactionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("transactionType")
  private TransactionTypeEnum transactionType = null;

  @SerializedName("value")
  private Integer value = null;

  public UpdateBalanceLimitPayload constraintType(ConstraintTypeEnum constraintType) {
    this.constraintType = constraintType;
    return this;
  }

   /**
   * Defines whether the limit applies to transaction count or amount.
   * @return constraintType
  **/
  @ApiModelProperty(required = true, value = "Defines whether the limit applies to transaction count or amount.")
  public ConstraintTypeEnum getConstraintType() {
    return constraintType;
  }

  public void setConstraintType(ConstraintTypeEnum constraintType) {
    this.constraintType = constraintType;
  }

  public UpdateBalanceLimitPayload durationUnit(DurationUnitEnum durationUnit) {
    this.durationUnit = durationUnit;
    return this;
  }

   /**
   * Unit of time for which the limit is applicable.
   * @return durationUnit
  **/
  @ApiModelProperty(required = true, value = "Unit of time for which the limit is applicable.")
  public DurationUnitEnum getDurationUnit() {
    return durationUnit;
  }

  public void setDurationUnit(DurationUnitEnum durationUnit) {
    this.durationUnit = durationUnit;
  }

  public UpdateBalanceLimitPayload durationValue(Integer durationValue) {
    this.durationValue = durationValue;
    return this;
  }

   /**
   * Number of time units for the balance limit.
   * @return durationValue
  **/
  @ApiModelProperty(required = true, value = "Number of time units for the balance limit.")
  public Integer getDurationValue() {
    return durationValue;
  }

  public void setDurationValue(Integer durationValue) {
    this.durationValue = durationValue;
  }

  public UpdateBalanceLimitPayload slidingSchedule(Boolean slidingSchedule) {
    this.slidingSchedule = slidingSchedule;
    return this;
  }

   /**
   * Determines if the limit resets on a rolling schedule.
   * @return slidingSchedule
  **/
  @ApiModelProperty(value = "Determines if the limit resets on a rolling schedule.")
  public Boolean isSlidingSchedule() {
    return slidingSchedule;
  }

  public void setSlidingSchedule(Boolean slidingSchedule) {
    this.slidingSchedule = slidingSchedule;
  }

  public UpdateBalanceLimitPayload transactionType(TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Specifies whether the limit applies to credit or debit transactions.
   * @return transactionType
  **/
  @ApiModelProperty(required = true, value = "Specifies whether the limit applies to credit or debit transactions.")
  public TransactionTypeEnum getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
  }

  public UpdateBalanceLimitPayload value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Maximum allowed value for the specified constraint type.
   * @return value
  **/
  @ApiModelProperty(required = true, value = "Maximum allowed value for the specified constraint type.")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    UpdateBalanceLimitPayload updateBalanceLimitPayload = (UpdateBalanceLimitPayload) o;
    return ObjectUtils.equals(this.constraintType, updateBalanceLimitPayload.constraintType) &&
    ObjectUtils.equals(this.durationUnit, updateBalanceLimitPayload.durationUnit) &&
    ObjectUtils.equals(this.durationValue, updateBalanceLimitPayload.durationValue) &&
    ObjectUtils.equals(this.slidingSchedule, updateBalanceLimitPayload.slidingSchedule) &&
    ObjectUtils.equals(this.transactionType, updateBalanceLimitPayload.transactionType) &&
    ObjectUtils.equals(this.value, updateBalanceLimitPayload.value);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(constraintType, durationUnit, durationValue, slidingSchedule, transactionType, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateBalanceLimitPayload {\n");
    
    sb.append("    constraintType: ").append(toIndentedString(constraintType)).append("\n");
    sb.append("    durationUnit: ").append(toIndentedString(durationUnit)).append("\n");
    sb.append("    durationValue: ").append(toIndentedString(durationValue)).append("\n");
    sb.append("    slidingSchedule: ").append(toIndentedString(slidingSchedule)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

