/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoApi;

import brevo.ApiException;
import brevoModel.*;
import org.junit.Ignore;
import java.util.ArrayList;
import org.junit.Test;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CouponsApi
 */
@Ignore
public class CouponsApiTest {

    private final CouponsApi api = new CouponsApi();

    
    /**
     * Create а coupon collection
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCouponCollectionTest() throws ApiException {
        CreateCouponCollection createCouponCollection = null;
        InlineResponse2013 response = api.createCouponCollection(createCouponCollection);

        // TODO: test validations
    }
    
    /**
     * Create coupons for a coupon collection
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCouponsTest() throws ApiException {
        CreateCoupons createCoupons = null;
        api.createCoupons(createCoupons);

        // TODO: test validations
    }
    
    /**
     * Get a coupon collection by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCouponCollectionTest() throws ApiException {
        String id = null;
        GetCouponCollection response = api.getCouponCollection(id);

        // TODO: test validations
    }
    
    /**
     * Get all your coupon collections
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCouponCollectionsTest() throws ApiException {
        Long limit = null;
        Long offset = null;
        String sort = null;
        String sortBy = null;
        GetCouponCollection response = api.getCouponCollections(limit, offset, sort, sortBy);

        // TODO: test validations
    }
    
    /**
     * Update a coupon collection by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCouponCollectionTest() throws ApiException {
        String id = null;
        UpdateCouponCollection updateCouponCollection = null;
        InlineResponse2009 response = api.updateCouponCollection(id, updateCouponCollection);

        // TODO: test validations
    }
    
}
