/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoApi;

import brevo.ApiException;
import brevoModel.AddSubscriptionMemberPayload;
import brevoModel.CreateLoyaltyProgramPayload;
import brevoModel.CreateSubscriptionPayload;
import brevoModel.ErrorResponse;
import brevoModel.LoyaltyProgram;
import brevoModel.LoyaltyProgramPage;
import brevoModel.PatchLoyaltyProgramPayload;
import brevoModel.Subscription;
import brevoModel.SubscriptionHandlerInfo;
import brevoModel.SubscriptionMember;
import java.util.UUID;
import brevoModel.UpdateLoyaltyProgramPayload;
import org.junit.Test;
import org.junit.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProgramApi
 */
@Ignore
public class ProgramApiTest {

    private final ProgramApi api = new ProgramApi();

    
    /**
     * Create loyalty program
     *
     * Creates loyalty program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNewLPTest() throws ApiException {
        CreateLoyaltyProgramPayload body = null;
        LoyaltyProgram response = api.createNewLP(body);

        // TODO: test validations
    }
    
    /**
     * Delete subscription member
     *
     * Deletes member from a subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteContactMembersTest() throws ApiException {
        UUID pid = null;
        String memberContactIds = null;
        api.deleteContactMembers(pid, memberContactIds);

        // TODO: test validations
    }
    
    /**
     * Delete Loyalty Program
     *
     * Deletes Loyalty Program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteLoyaltyProgramTest() throws ApiException {
        UUID pid = null;
        api.deleteLoyaltyProgram(pid);

        // TODO: test validations
    }
    
    /**
     * Get loyalty program list
     *
     * Returns list of loyalty programs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLPListTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String sortField = null;
        String sort = null;
        LoyaltyProgramPage response = api.getLPList(limit, offset, sortField, sort);

        // TODO: test validations
    }
    
    /**
     * Get loyalty program Info
     *
     * Returns loyalty program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoyaltyProgramInfoTest() throws ApiException {
        UUID pid = null;
        LoyaltyProgram response = api.getLoyaltyProgramInfo(pid);

        // TODO: test validations
    }
    
    /**
     * Get Subscription Data
     *
     * Get Information of balances, tiers, rewards and subscription members for a subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getParameterSubscriptionInfoTest() throws ApiException {
        UUID pid = null;
        String contactId = null;
        String params = null;
        String loyaltySubscriptionId = null;
        SubscriptionHandlerInfo response = api.getParameterSubscriptionInfo(pid, contactId, params, loyaltySubscriptionId);

        // TODO: test validations
    }
    
    /**
     * Partially update loyalty program
     *
     * Partially updates loyalty program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void partiallyUpdateLoyaltyProgramTest() throws ApiException {
        UUID pid = null;
        PatchLoyaltyProgramPayload body = null;
        LoyaltyProgram response = api.partiallyUpdateLoyaltyProgram(pid, body);

        // TODO: test validations
    }
    
    /**
     * Publish loyalty program
     *
     * Publishes loyalty program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publishLoyaltyProgramTest() throws ApiException {
        UUID pid = null;
        api.publishLoyaltyProgram(pid);

        // TODO: test validations
    }
    
    /**
     * Create subscription member
     *
     * Add member to a subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subscribeMemberToASubscriptionTest() throws ApiException {
        UUID pid = null;
        AddSubscriptionMemberPayload body = null;
        SubscriptionMember response = api.subscribeMemberToASubscription(pid, body);

        // TODO: test validations
    }
    
    /**
     * Create subscription
     *
     * Subscribes to a loyalty program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subscribeToLoyaltyProgramTest() throws ApiException {
        UUID pid = null;
        CreateSubscriptionPayload body = null;
        Subscription response = api.subscribeToLoyaltyProgram(pid, body);

        // TODO: test validations
    }
    
    /**
     * Update loyalty program
     *
     * Updates loyalty program
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateLoyaltyProgramTest() throws ApiException {
        UUID pid = null;
        UpdateLoyaltyProgramPayload body = null;
        LoyaltyProgram response = api.updateLoyaltyProgram(pid, body);

        // TODO: test validations
    }
    
}
